// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReimbursementTrackerApp.Contexts;

#nullable disable

namespace ReimbursementTrackerApp.Migrations
{
    [DbContext(typeof(ReimbursementDbContext))]
    [Migration("20260318111718_AddAttachmentPathToReimbursement")]
    partial class AddAttachmentPathToReimbursement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Approval.ApprovalHistory", b =>
                {
                    b.Property<Guid>("ApprovalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApprovalStage")
                        .HasColumnType("int");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReimbursementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ApprovalHistoryId");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("ReimbursementRequestId");

                    b.ToTable("ApprovalHistories");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Identity.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Identity.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Notification.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Payment.PaymentRecord", b =>
                {
                    b.Property<Guid>("PaymentRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<Guid>("ReimbursementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentRecordId");

                    b.HasIndex("ReimbursementRequestId");

                    b.ToTable("PaymentRecords");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Policy.PolicyRule", b =>
                {
                    b.Property<Guid>("PolicyRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaximumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RuleType")
                        .HasColumnType("int");

                    b.HasKey("PolicyRuleId");

                    b.ToTable("PolicyRules");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Policy.PolicyViolation", b =>
                {
                    b.Property<Guid>("PolicyViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PolicyRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReimbursementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ViolationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolicyViolationId");

                    b.HasIndex("PolicyRuleId");

                    b.HasIndex("ReimbursementRequestId");

                    b.ToTable("PolicyViolations");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Reimbursement.ExpenseCategory", b =>
                {
                    b.Property<Guid>("ExpenseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ExpenseCategoryId");

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            ExpenseCategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CategoryName = "Travel",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExpenseCategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CategoryName = "Food",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExpenseCategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CategoryName = "Accommodation",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementAttachment", b =>
                {
                    b.Property<Guid>("ReimbursementAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReimbursementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReimbursementAttachmentId");

                    b.HasIndex("ReimbursementRequestId");

                    b.ToTable("ReimbursementAttachments");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementRequest", b =>
                {
                    b.Property<Guid>("ReimbursementRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExpenseCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReimbursementRequestId");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ReimbursementRequests");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementStatusHistory", b =>
                {
                    b.Property<Guid>("ReimbursementStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ReimbursementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReimbursementStatusHistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ReimbursementRequestId");

                    b.ToTable("ReimbursementStatusHistories");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.UserManagement.BankDetail", b =>
                {
                    b.Property<Guid>("BankDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BankDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.UserManagement.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.UserManagement.UserProfile", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserProfileId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Approval.ApprovalHistory", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.Identity.User", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementRequest", "ReimbursementRequest")
                        .WithMany()
                        .HasForeignKey("ReimbursementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverUser");

                    b.Navigation("ReimbursementRequest");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Identity.RefreshToken", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Identity.User", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.Identity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Notification.Notification", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Payment.PaymentRecord", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementRequest", "ReimbursementRequest")
                        .WithMany()
                        .HasForeignKey("ReimbursementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReimbursementRequest");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Policy.PolicyViolation", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.Policy.PolicyRule", "PolicyRule")
                        .WithMany()
                        .HasForeignKey("PolicyRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementRequest", "ReimbursementRequest")
                        .WithMany()
                        .HasForeignKey("ReimbursementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyRule");

                    b.Navigation("ReimbursementRequest");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementAttachment", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementRequest", "ReimbursementRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("ReimbursementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReimbursementRequest");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementRequest", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.Reimbursement.ExpenseCategory", "ExpenseCategory")
                        .WithMany("ReimbursementRequests")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReimbursementTrackerApp.Models.Identity.User", "User")
                        .WithMany("ReimbursementRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementStatusHistory", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.Identity.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementRequest", "ReimbursementRequest")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ReimbursementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("ReimbursementRequest");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.UserManagement.BankDetail", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.UserManagement.UserProfile", b =>
                {
                    b.HasOne("ReimbursementTrackerApp.Models.UserManagement.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ReimbursementTrackerApp.Models.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Identity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Identity.User", b =>
                {
                    b.Navigation("ReimbursementRequests");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Reimbursement.ExpenseCategory", b =>
                {
                    b.Navigation("ReimbursementRequests");
                });

            modelBuilder.Entity("ReimbursementTrackerApp.Models.Reimbursement.ReimbursementRequest", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
